### PR TITLE
fix : fix doc links in README.md

### LINKED ISSUE #50: 403 when accessing the docs
There seems to be something wrong when accessing the docs, I have a 403 at https://docs.sciml.ai/NeuralOperators/stable/.

### PR DESCRIPTION
**Pull request by ayushinav**
fix #50

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
No, we should fix the stable docs, not just link to the dev docs. @thazhemadam can you look into what's going on? @avik-pal setup API keys but it seems to not do it.

**Comment by ChrisRackauckas** [comment]
Oh @avik-pal yes, it's using Buildkite for the docs so it needs some extra key stuff that I never understood but @thazhemadam knows how to do.

**Comment by avik-pal** [comment]
build tags on buildkite was disabled for some reason. I will add the keys and cut a release

**Comment by avik-pal** [comment]
https://sciml.github.io/NeuralOperators.jl/stable/

**Comment by avik-pal** [comment]
https://docs.sciml.ai/NeuralOperators/stable/ will eventually pick it up i guess?

**Comment by ChrisRackauckas** [comment]
It should rebuild every 4 hours

**Pull request closed without merging**
